/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mx_ipn_www_finalproject_utils_BinarySelection */

#ifndef _Included_mx_ipn_www_finalproject_utils_BinarySelection
#define _Included_mx_ipn_www_finalproject_utils_BinarySelection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mx_ipn_www_finalproject_utils_BinarySelection
 * Method:    getAlimento
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mx_ipn_www_finalproject_utils_BinarySelection_getAlimento
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     mx_ipn_www_finalproject_utils_BinarySelection
 * Method:    getCantidad
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mx_ipn_www_finalproject_utils_BinarySelection_getCantidad
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     mx_ipn_www_finalproject_utils_BinarySelection
 * Method:    cross
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mx_ipn_www_finalproject_utils_BinarySelection_cross
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     mx_ipn_www_finalproject_utils_BinarySelection
 * Method:    mutation
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mx_ipn_www_finalproject_utils_BinarySelection_mutation
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
