-- MySQL Script generated by MySQL Workbench
-- jue 16 may 2019 03:21:55 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CategoriaAlimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CategoriaAlimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CategoriaAlimento` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreCategoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Alimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alimento` (
  `idAlimento` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cantidad` DOUBLE NOT NULL,
  `Unidad` VARCHAR(45) NULL DEFAULT NULL,
  `Proteinas` DOUBLE NOT NULL,
  `Lipidos` DOUBLE NOT NULL,
  `Carbohidratos` DOUBLE NOT NULL,
  `Estado` INT(1) NOT NULL,
  `Categoria` INT(11) NOT NULL,
  PRIMARY KEY (`idAlimento`),
  CONSTRAINT `CategoriaDelAliemtno`
    FOREIGN KEY (`Categoria`)
    REFERENCES `mydb`.`CategoriaAlimento` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `CategoriaDelAliemtno_idx` ON `mydb`.`Alimento` (`Categoria` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`AlimentosEquivalentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AlimentosEquivalentes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AlimentosEquivalentes` (
  `idAlimentosEquivalentes` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cantidad` DOUBLE NOT NULL,
  `Proteinas` DOUBLE NOT NULL,
  `Lipidos` DOUBLE NOT NULL,
  `Carbohidratos` DOUBLE NOT NULL,
  PRIMARY KEY (`idAlimentosEquivalentes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Correo` VARCHAR(45) NOT NULL,
  `Pass` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `Correo_UNIQUE` ON `mydb`.`Usuario` (`Correo` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Nutricionista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nutricionista` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nutricionista` (
  `idNutricionista` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cedula` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `EscuelaProcedencia` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Estado` INT(1) NOT NULL,
  `FechaRegistro` DATETIME NOT NULL,
  `FechaAceptado` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idNutricionista`),
  CONSTRAINT `fk_Nutricionista_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `Usuario_idUsuario_UNIQUE` ON `mydb`.`Nutricionista` (`Usuario_idUsuario` ASC);

CREATE INDEX `fk_Nutricionista_Usuario_idx` ON `mydb`.`Nutricionista` (`Usuario_idUsuario` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT(11) NOT NULL,
  `Nutricionista_idNutricionista` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(80) NOT NULL,
  `PesoAnterior` DOUBLE NOT NULL,
  `Estatura` DOUBLE NOT NULL,
  `CirBraquial` DOUBLE NOT NULL,
  `CirPantorrilla` DOUBLE NOT NULL,
  `DificultadesAliment` VARCHAR(80) NULL DEFAULT NULL,
  `Enfermedades` VARCHAR(80) NULL DEFAULT NULL,
  `Tratamiento` VARCHAR(80) NULL DEFAULT NULL,
  `ProteinaAnterior` DOUBLE NOT NULL,
  `LipidosAnterior` DOUBLE NOT NULL,
  `CarbohidratosAnterior` DOUBLE NOT NULL,
  `ComidasAnterior` DOUBLE NOT NULL,
  `ActividadFisica` INT(1) NOT NULL,
  `FechaRegistro` DATE NOT NULL,
  `Estado` INT(1) NOT NULL,
  PRIMARY KEY (`idPaciente`),
  CONSTRAINT `fk_Paciente_Nutricionista1`
    FOREIGN KEY (`Nutricionista_idNutricionista`)
    REFERENCES `mydb`.`Nutricionista` (`idNutricionista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Paciente_Usuario1_idx` ON `mydb`.`Paciente` (`Usuario_idUsuario` ASC);

CREATE INDEX `fk_Paciente_Nutricionista1_idx` ON `mydb`.`Paciente` (`Nutricionista_idNutricionista` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`AlimentosExcluidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AlimentosExcluidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AlimentosExcluidos` (
  `Paciente_idPaciente` INT(11) NOT NULL,
  `Alimento_idAlimento` INT(11) NOT NULL,
  PRIMARY KEY (`Paciente_idPaciente`, `Alimento_idAlimento`),
  CONSTRAINT `fk_AlimentosExcluidos_Alimento1`
    FOREIGN KEY (`Alimento_idAlimento`)
    REFERENCES `mydb`.`Alimento` (`idAlimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlimentosExcluidos_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_AlimentosExcluidos_Paciente1_idx` ON `mydb`.`AlimentosExcluidos` (`Paciente_idPaciente` ASC);

CREATE INDEX `fk_AlimentosExcluidos_Alimento1_idx` ON `mydb`.`AlimentosExcluidos` (`Alimento_idAlimento` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`PlanAlimenticio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PlanAlimenticio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PlanAlimenticio` (
  `idPlanAlimenticio` INT(11) NOT NULL AUTO_INCREMENT,
  `Paciente_idPaciente` INT(11) NOT NULL,
  `FechaCreacion` DATE NOT NULL,
  `Duracion` INT(11) NOT NULL,
  `NoComidas` INT(11) NOT NULL,
  `Estado` INT(1) NOT NULL,
  `Proteinas` DOUBLE NOT NULL,
  `Lipidos` DOUBLE NOT NULL,
  `Carbohidratos` DOUBLE NOT NULL,
  `GastoCalorico` DOUBLE NULL DEFAULT NULL,
  `TMR` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idPlanAlimenticio`),
  CONSTRAINT `fk_PlanAlimenticio_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_PlanAlimenticio_Paciente1_idx` ON `mydb`.`PlanAlimenticio` (`Paciente_idPaciente` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Comida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comida` (
  `idComida` INT(11) NOT NULL AUTO_INCREMENT,
  `PlanAlimenticio_idPlanAlimenticio` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Dia` VARCHAR(45) NOT NULL,
  `Numero` INT(11) NOT NULL,
  `Hora` TIME NOT NULL,
  PRIMARY KEY (`idComida`),
  CONSTRAINT `fk_Comida_PlanAlimenticio1`
    FOREIGN KEY (`PlanAlimenticio_idPlanAlimenticio`)
    REFERENCES `mydb`.`PlanAlimenticio` (`idPlanAlimenticio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Comida_PlanAlimenticio1_idx` ON `mydb`.`Comida` (`PlanAlimenticio_idPlanAlimenticio` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`HistorialAntropometrico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HistorialAntropometrico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HistorialAntropometrico` (
  `idRegistro` INT(11) NOT NULL AUTO_INCREMENT,
  `Paciente_idPaciente` INT(11) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Peso` DOUBLE NOT NULL,
  `IMC` DOUBLE NOT NULL,
  `Grasa` DOUBLE NOT NULL,
  PRIMARY KEY (`idRegistro`),
  CONSTRAINT `fk_Registro_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Registro_Paciente1_idx` ON `mydb`.`HistorialAntropometrico` (`Paciente_idPaciente` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Rel_comida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rel_comida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rel_comida` (
  `Comida_idComida` INT(11) NOT NULL,
  `Alimento_idAlimento` INT(11) NOT NULL,
  `Cantidad` INT(3) NOT NULL,
  PRIMARY KEY (`Comida_idComida`, `Alimento_idAlimento`),
  CONSTRAINT `fk_Rel_comida_Alimento1`
    FOREIGN KEY (`Alimento_idAlimento`)
    REFERENCES `mydb`.`Alimento` (`idAlimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rel_comida_Comida1`
    FOREIGN KEY (`Comida_idComida`)
    REFERENCES `mydb`.`Comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Rel_comida_Comida1_idx` ON `mydb`.`Rel_comida` (`Comida_idComida` ASC);

CREATE INDEX `fk_Rel_comida_Alimento1_idx` ON `mydb`.`Rel_comida` (`Alimento_idAlimento` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Seguimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Seguimiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Seguimiento` (
  `idSeguimiento` INT(11) NOT NULL AUTO_INCREMENT,
  `Cumplimiento` VARCHAR(45) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Comida_idComida` INT(11) NOT NULL,
  `AlimentosEquivalentes_idAlimentosEquivalentes` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idSeguimiento`),
  CONSTRAINT `fk_Seguimiento_AlimentosEquivalentes1`
    FOREIGN KEY (`AlimentosEquivalentes_idAlimentosEquivalentes`)
    REFERENCES `mydb`.`AlimentosEquivalentes` (`idAlimentosEquivalentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seguimiento_Comida1`
    FOREIGN KEY (`Comida_idComida`)
    REFERENCES `mydb`.`Comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Seguimiento_Comida1_idx` ON `mydb`.`Seguimiento` (`Comida_idComida` ASC);

CREATE INDEX `fk_Seguimiento_AlimentosEquivalentes1_idx` ON `mydb`.`Seguimiento` (`AlimentosEquivalentes_idAlimentosEquivalentes` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
